---
- name: Playbook to get ASG EC2 Hosts
  hosts: localhost
  gather_facts: false
  become: false

  tasks:

  - name: Get the BLUE auto scaling group instances
    ec2_asg_info:
    name: WebServer
    register: all_asgs
  - set_fact:
      asg_blue_id: "{{ all_asgs.results|map(attribute='tags')|sum(start=[])|selectattr('value', 'equalto', 'Blue')|json_query('[].resource_id') | list }}"
  - set_fact:
      ec2_instaces_blue: "{{ all_asgs.results|selectattr('auto_scaling_group_name', 'equalto', asg_blue_id[0])|map(attribute='instances')|json_query('[][].instance_id') }}"

  - name: Get BLUE EC2 Instances Info
    ec2_instance_info:
      instance_ids: '{{ item }}'
    with_items: "{{ ec2_instaces_blue }}"
    register: ec2s
  - set_fact:
      private_dns_names: "{{ec2s.results|map(attribute='instances')|json_query('[][].network_interfaces')|json_query('[][].private_dns_name')|list }}"
  # - debug:
      # msg: "{{ private_dns_names }}"
  
  - name: Group BLUE Hosts with EC2 private dns names
    add_host: hostname={{ item }} groups=backendservers
    with_items: "{{ private_dns_names }}"

  - name: Get BASTION_HOST
    ec2_instance_info:
      filters:
        key-name: ec2acc
    register: bastion_host
  - set_fact:
      BASTION_HOST: "{{ bastion_host.instances|map(attribute='network_interfaces')|sum(start=[])|json_query('[?association]')|map(attribute='association')|json_query('[].public_dns_name')}}"
  # - debug: 
  #     msg: "{{ BASTION_HOST }}"

- name: playbook deploy the node backend
  hosts: backendservers
  gather_facts: false
  become: true
  vars:
    BASTION_HOST: "{{ hostvars['localhost']['BASTION_HOST'][0] }}"
    DatabaseSecretName: "{{ lookup('env','DatabaseSecretName') }}"
    POSTGRES_INFO: "{{ lookup('amazon.aws.aws_secret', '{{ DatabaseSecretName }}' , region='us-east-1') }}"
  environment:
    POSTGRES_USERNAME: "{{ POSTGRES_INFO.username }}"
    POSTGRES_PASSWORD: "{{ POSTGRES_INFO.password }}"
    POSTGRES_HOST: "{{ lookup('env','POSTGRES_HOST') }}"
    POSTGRES_DB: "{{ lookup('env','POSTGRES_DB') }}"
    PORT: "{{ lookup('env','PORT') }}"
    JWT_SECRET: "{{ lookup('env','JWT_SECRET') }}"
  
  tasks:
  - name: Write the new ec2 instances host key to known hosts
    connection: local
    shell: "ssh-keyscan -H {{ BASTION_HOST  }} >> ~/.ssh/known_hosts"
    become: false

  - set_fact:
      ansible_ssh_common_args: -o ProxyCommand="ssh -q ubuntu@{{ BASTION_HOST }} -W %h:%p"
      ansible_user: ubuntu
      
  - name: Stop current running backend server
    shell:
      cmd: killall node
    ignore_errors: yes

  - name: Clean old server files
    shell:
      cmd: rm -rf Archive.zip node_modules/ package*.json www/
      chdir: /var/app/current/

  - name: Copy Build Zip File
    copy:
      src: ../Archive.zip
      dest: /var/app/current
  
  - name: Unzip Build File
    shell:
      cmd: unzip Archive.zip
      chdir: /var/app/current/

  - name: Install node_modules
    shell:
      cmd: npm install
      chdir: /var/app/current/

  - name: Start the server
    shell:
      cmd: npm run start &
      chdir: /var/app/current/
    register: npm_status
  - debug: var=npm_status.stdout
    

  - name: Confirm backend server is running
    shell: 
      cmd: ps -ef | grep -v grep | grep node
    register: npm_output
    failed_when: "'node' not in npm_output.stdout"