---
- name: Playbook to get ASG EC2 Hosts
  hosts: localhost
  gather_facts: false
  become: false

  tasks:

  - name: Get the auto scaling group instances
    ec2_asg_info:
    name: WebServer
    register: asg_ec2_instance_ids
  # - debug: var=asg_ec2_instance_ids.results[0].instances|map(attribute='instance_id')|list

  - name: Get EC2 Instances Info
    ec2_instance_info:
      instance_ids: '{{ item }}'
    with_items: "{{ asg_ec2_instance_ids.results[0].instances|map(attribute='instance_id')|list }}"
    register: ec2s
  # - debug: var=ec2s.results|map(attribute='instances')|sum(start=[])|map(attribute='network_interfaces')|sum(start=[])|map(attribute='private_dns_name')|list
  
  - name: Group Hosts with EC2 private dns names
    add_host: hostname={{ item }} groups=backendservers
    with_items: "{{ ec2s.results|map(attribute='instances')|sum(start=[])|map(attribute='network_interfaces')|sum(start=[])|map(attribute='private_dns_name')|list }}"

  - name: Get BASTION_HOST
    ec2_instance_info:
      filters:
        key-name: ec2acc
    register: bastion_host
  - set_fact:
      BASTION_HOST: "{{ bastion_host.instances|map(attribute='network_interfaces')|sum(start=[])|json_query('[?association]')|map(attribute='association')|json_query('[].public_dns_name')}}"
  # - debug: 
  #     msg: "{{ BASTION_HOST }}"

- name: playbook deploy the node backend
  hosts: backendservers
  gather_facts: false
  become: true
  vars:
    BASTION_HOST: "{{ hostvars['localhost']['BASTION_HOST'][0] }}"
    AWS_REGION: "{{ lookup('env','AWS_REGION') }}"
    POSTGRES_INFO: "{{ lookup('amazon.aws.aws_secret', 'PgSQLSecret-jx92GxHf3nlK', region='{{ AWS_REGION }}') }}"
  environment:
    POSTGRES_USERNAME: "{{ POSTGRES_INFO.username) }}"
    POSTGRES_PASSWORD: "{{ POSTGRES_INFO.password }}"
    # POSTGRES_USERNAME: "{{ lookup('env','POSTGRES_USERNAME') }}"
    # POSTGRES_PASSWORD: "{{ lookup('env','POSTGRES_PASSWORD') }}"
    POSTGRES_HOST: "{{ lookup('env','POSTGRES_HOST') }}"
    POSTGRES_DB: "{{ lookup('env','POSTGRES_DB') }}"
    PORT: "{{ lookup('env','PORT') }}"
    JWT_SECRET: "{{ lookup('env','JWT_SECRET') }}"
  
  tasks:
  - name: Write the new ec2 instances host key to known hosts
    connection: local
    shell: "ssh-keyscan -H {{ BASTION_HOST  }} >> ~/.ssh/known_hosts"
    become: false

  - set_fact:
      ansible_ssh_common_args: -o ProxyCommand="ssh -q ubuntu@{{ BASTION_HOST }} -W %h:%p"
      ansible_user: ubuntu
      
  - name: Stop current running backend server
    shell:
      cmd: killall node
    ignore_errors: yes

  - name: Clean old server files
    shell:
      cmd: rm -rf Archive.zip node_modules/ package*.json www/
      chdir: /var/app/current/

  - name: Copy Build Zip File
    copy:
      src: ../Archive.zip
      dest: /var/app/current
  
  - name: Unzip Build File
    shell:
      cmd: unzip Archive.zip
      chdir: /var/app/current/

  - name: Install node_modules
    shell:
      cmd: npm install
      chdir: /var/app/current/

  - name: Start the server
    shell:
      cmd: npm run start &
      chdir: /var/app/current/

  - name: Confirm backend server is running
    shell: 
      cmd: ps -ef | grep -v grep | grep node
    register: npm_output
    failed_when: "'node' not in npm_output.stdout"
# - debug: var=npm_output.stdout