---
- name: Playbook to get ASG EC2 Hosts
  hosts: localhost
  gather_facts: false
  become: false

  tasks:

  - name: Get the BLUE auto scaling group instances
    ec2_asg_info:
    name: WebServer
    register: all_asgs
  - debug:
      msg: "{{ all_asgs }}"
  - set_fact:
      asg_blue_id: "{{ all_asgs.results|map(attribute='tags')|sum(start=[])|selectattr('value', 'equalto', 'Blue')|json_query('[].resource_id') | list }}"
  - set_fact:
      ec2_instaces_blue: "{{ all_asgs.results|selectattr('auto_scaling_group_name', 'equalto', asg_blue_id[0])|map(attribute='instances')|sum(start=[])|selectattr('health_status', 'equalto', 'Healthy')|json_query('[].instance_id') }}"
  - debug:
      msg: "{{ ec2_instaces_blue }}"
  - debug: 
      msg: "{{ asg_blue_id }}"

  - name: Get EC2 Instances Info
    ec2_instance_info:
      instance_ids: '{{ item }}'
    with_items: "{{ ec2_instaces_blue }}"
    register: ec2s
  - set_fact:
      private_dns_names: "{{ec2s.results|map(attribute='instances')|json_query('[][].network_interfaces')|json_query('[][].private_dns_name')|list }}"
  - debug:
      msg: "{{ private_dns_names }}"
